apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: missbot
  annotations:
    reloader.stakater.com/auto: "true"
  name: missbot
  namespace: misskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: missbot
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: missbot
    spec:
      shareProcessNamespace: true
      containers:
        - image: lax.vultrcr.com/mercury/korg:latest
          imagePullPolicy: Always
          name: bot
          env:
            - name: LOGFIRE_SERVICE_NAME
              value: missbot
            - name: LOGFIRE_ENVIRONMENT
              value: k8s
          envFrom:
            - secretRef:
                name: missbot-secrets
          volumeMounts:
            - name: config-volume
              mountPath: /config.yaml
              subPath: config.yaml
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: config-volume
          configMap:
            name: missbot-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: rachels-mac-mini.taile6e57.ts.net
  name: rachels-mac-mini
  namespace: misskey
spec:
  type: ExternalName
